export * from './bloque.repository';
export * from './ciudad.repository';
export * from './cliente-inf-fina.repository';
export * from './cliente.repository';
export * from './inmueble.repository';
export * from './pais.repository';
export * from './proyecto.repository';
export * from './registro-pago.repository';
export * from './solicitud.repository';
